export const THEME_COLORS = {
    primary: '#df103f',
    secondary: '#ff8c4c',
    background: '#f7fafc',
    surface: '#fff',
    error: '#f44336',
    text: '#334155',
    disabled: '#f0f0f0',
    placeholder: '#aaa',
};


export const VIDEOS_TEMPLATES = [
    {
        id: 1,
        title: "Social Media Promo",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_1.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_1.mp4",
    },
    {
        id: 2,
        title: "Product Showcase",
        width: 440, 
        height: 780,
        thumbnail: "assets/images/video/v_2.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_2.mp4",
    },
    {
        id: 3,
        title: "Event Announcement",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_3.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_3.mp4",
    },
    {
        id: 4,
        title: "Brand Story",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_4.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_4.mp4",
    },
    {
        id: 5,
        title: "Tutorial Video",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_5.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_5.mp4",
    },
    {
        id: 6,
        title: "Customer Testimonial",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_6.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_6.mp4",
    },
    {
        id: 7,
        title: "Seasonal Sale",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_7.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_7.mp4",
    },
    {
        id: 8,
        title: "Behind the Scenes",
        width: 440,
        height: 780,
        thumbnail: "assets/images/video/v_8.png",
        videoURL: "https://api.flarelap.com/videos/flarelap_video_8.mp4",
    },
]