export const API_ROUTES = {
  LOGIN: '/auth/login',
  LOGOUT: '/auth/logout',
  SIGNUP: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  VERIFY_OTP: '/auth/verify-otp',
  RESET_PASSWORD: '/auth/reset-password',
  REFRESH_TOKEN: '/auth/refresh',
  GOOGLE_LOGIN: '/auth/mobile/google',
  FACEBOOK_LOGIN: '/auth/mobile/facebook',
  APPLE_LOGIN: '/auth/mobile/apple',
  USER: '/user',
  USER_PROFILE: '/user/profile',
  TEMPLATES: '/templates',
  TRENDING_TEMPLATES: '/templates/trending',
  SVG_TO_FABRIC: '/image/svg-to-fabric', 
};
